name: Bash Assignment 1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Bash
      uses: actions/setup-bash@v1

    - name: Make script executable
      run: chmod +x myscript.sh

    - name: Run script
      run: ./myscript.sh

    - name: Run unit tests
      run: |
        echo "Running tests..."
        # If there is a test file from Coursera, put the command here
        # Example:
        # bash test_assignment1.sh
